version: '3.4'

services:
  elevador:
    container_name: Elevator
    image: ${DOCKER_REGISTRY-}elevador
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: QA
    depends_on:
            - db
    ports:
     - 5240:80
  db:
     container_name: sqlDB
     image: "mcr.microsoft.com/mssql/server"
     environment:
       SA_PASSWORD: "MyPassword001"
       ACCEPT_EULA: "Y"
